stages:
  - testing
  - packaging

before_script:
  - export CURRENT_COMMIT_NO=$(git rev-list --count $CI_COMMIT_SHA)

  - pip install -U pip wheel

  - pip install -U -r setup-requirements.txt
  - pip install -U -r test-requirements.txt

  - pip install --editable .

  - pip install -U codecov coverage

testing-3-6-linux:
  image: python:3.6
  stage: testing

  script:
    - mypy --python-version 3.6 --disallow-untyped-calls --disallow-untyped-defs --warn-unused-ignores --show-traceback --strict-optional --ignore-missing-imports --show-error-context magicdict
    - flake8 .
    - python -m coverage run --source=magicdict setup.py test

    - export SCRIPT_SUCCEED="1"

  after_script:
    - if [[ "$SCRIPT_SUCCEED" == "1" ]]; then codecov --token=$CODECOV_TOKEN --branch=$CI_BUILD_REF_NAME ; fi

packaging-3-6-linux:
  image: python:3.6
  stage: packaging

  script:
    - python setup.py sdist bdist_wheel

  artifacts:
    paths:
      - dist/
